### PR TITLE
Play an attchement video using the Video.js library

### PR DESCRIPTION
**Pull request by mouhb**
In this PR I added the possibility to play a video attachment using Video.js library (http://www.videojs.com/)

Added macro parameters : 
- attachment : This parameter is a boolean that indicates if the video is an URL or an attachment. The default value is false.
- attachmentName : The name of the video attachment
- videoPoster : The poster of the video is an image attachment that will be displayed before starting playing the video.

For the moment the videos formats supported are : mp4, webm and ogv

### CODE REVIEW

**Comment by vmassol** [comment]
Has this been documented at http://extensions.xwiki.org/xwiki/bin/view/Extension/Video+Macro ? doesnt seem so.

**Comment by Enygma2002** [comment]
Really nice feature that we were really missing!

Either the developer ( @mouhb ) or the 1.6 release manager ( @cjdelisle ) should add a few lines of documentation on the extension page or users will never know about it!

**Comment by mouhb** [comment]
Thanks for your comments. I will check all ASAP.

**Comment by mflorea** [comment]
> Really nice feature that we were really missing!

@Enygma2002 [JW Player Macro](http://extensions.xwiki.org/xwiki/bin/view/Extension/JW+Player+Macro) does this since a long time.

**Pull request merged**
